apiVersion: v1
kind: Service
metadata:
  name: hello-world-loadbalancer
  namespace: hello-world
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080